# Generated by Django 4.0.3 on 2022-04-15 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='大学名')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('openingSystem', models.CharField(choices=[('昼間主', '昼間主'), ('夜間主', '夜間主')], max_length=10, verbose_name='昼間主・夜間主')),
                ('department', models.CharField(choices=[('', '選択してください（必須）'), ('人文社会学部', '人文社会学部'), ('国際地域創造学部', '国際地域創造学部'), ('教育学部', '教育学部'), ('理学部', '理学部'), ('医学部', '医学部'), ('工学部', '工学部'), ('農学部', '農学部')], max_length=20, verbose_name='学部')),
                ('subject', models.CharField(choices=[('', '選択してください（必須）'), ('国際地域創造学科', '国際地域創造学科')], max_length=20, verbose_name='学科・課程')),
                ('course', models.CharField(blank=True, choices=[('', '選択してください（任意）')], max_length=20, null=True, verbose_name='プログラム、コース')),
                ('major', models.CharField(blank=True, choices=[('', '選択してください（任意）')], max_length=20, null=True, verbose_name='専攻')),
                ('specialization', models.CharField(blank=True, choices=[('', '選択してください（任意）')], max_length=20, null=True, verbose_name='専修')),
                ('graduationYear', models.CharField(choices=[('', '選択してください（必須）'), ('2022年', '2022年'), ('2023年', '2023年'), ('2024年', '2024年'), ('2025年', '2025年')], max_length=10, verbose_name='卒業見込み年')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='琉大メールアドレス')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university', verbose_name='大学名')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
