# Generated by Django 4.0.3 on 2022-07-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='graduationYear',
            field=models.IntegerField(choices=[('', '選択してください（必須）'), (2022, '2022年'), (2023, '2023年'), (2024, '2024年'), (2025, '2025年')], default=2024, verbose_name='卒業見込み年'),
        ),
    ]
