# Generated by Django 4.0.3 on 2022-07-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_graduationyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='graduationYear',
            field=models.IntegerField(choices=[('', '選択してください（必須）'), (2022, '2022年'), (2023, '2023年'), (2024, '2024年'), (2025, '2025年')], verbose_name='卒業見込み年'),
        ),
    ]
