# Generated by Django 4.0.3 on 2022-07-25 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='講義名')),
                ('subject_class', models.CharField(choices=[('', '選択してください（必須）'), ('共通教育', '共通教育'), ('人文社会学部専門教育', '人文社会学部専門教育'), ('国際地域創造学部専門教育', '国際地域創造学部専門教育')], max_length=30, verbose_name='講義分類')),
                ('subject_detail', models.CharField(choices=[('', '選択してください（必須）'), ('健康運動系科目', '健康運動系科目'), ('人文系科目', '人文系科目'), ('社会系科目', '社会系科目'), ('自然系科目', '自然系科目'), ('総合科目', '総合科目'), ('琉大特色科目・地域創生科目', '琉大特色科目・地域創生科目'), ('キャリア関係科目', 'キャリア関係科目'), ('情報関係科目', '情報関係科目'), ('平和共生・沖縄理解科目群', '平和共生・沖縄理解科目群'), ('外国語科目', '外国語科目'), ('学部共通基盤科目', '学部共通基盤科目'), ('平和共生・沖縄理解基盤科目', '平和共生・沖縄理解基盤科目'), ('学科基盤科目', '学科基盤科目'), ('学科発展科目', '学科発展科目'), ('プログラム基盤科目', 'プログラム基盤科目'), ('プログラム発展科目', 'プログラム発展科目'), ('プログラムコア基礎科目', 'プログラムコア基礎科目'), ('プログラムコア発展科目', 'プログラムコア発展科目'), ('専門基盤力科目', '専門基盤力科目'), ('地域・国際基盤力科目（プログラム系科目）', '地域・国際基盤力科目（プログラム系科目）'), ('地域・国際基盤力科目（プログラム複合科目）', '地域・国際基盤力科目（プログラム複合科目）'), ('観光地域デザインプログラム専門科目（基礎科目）', '観光地域デザインプログラム専門科目（基礎科目）'), ('観光地域デザインプログラム専門科目（応用科目）', '観光地域デザインプログラム専門科目（応用科目）'), ('観光地域デザインプログラム専門科目（地域・国際実践力科目）', '観光地域デザインプログラム専門科目（地域・国際実践力科目）'), ('経営プログラム専門科目（基礎科目）', '経営プログラム専門科目（基礎科目）'), ('経営プログラム専門科目（応用科目）', '経営プログラム専門科目（応用科目）'), ('経営プログラム専門科目（地域・国際実践力科目）', '経営プログラム専門科目（地域・国際実践力科目）'), ('経済学プログラム専門科目（基礎科目）', '経済学プログラム専門科目（基礎科目）'), ('経済学プログラム専門科目（応用科目）', '経済学プログラム専門科目（応用科目）'), ('経済学プログラム専門科目（地域・国際実践力科目）', '経済学プログラム（地域・国際実践力科目）'), ('国際言語文化プログラム専門科目（基礎科目）', '国際言語文化プログラム専門科目（基礎科目）'), ('国際言語文化プログラム専門科目（応用科目）', '国際言語文化プログラム専門科目（応用科目）'), ('国際言語文化プログラム専門科目（地域・国際実践力科目）', '国際言語文化プログラム専門科目（地域・国際実践力科目）'), ('地域文化科学プログラム専門科目（基礎科目）', '地域文化科学プログラム専門科目（基礎科目）'), ('地域文化科学プログラム専門科目（応用科目）', '地域文化科学プログラム専門科目（応用科目）'), ('地域文化科学プログラム専門科目（地域・国際実践力科目）', '地域文化科学プログラム専門科目（地域・国際実践力科目）'), ('教職課程', '教職課程')], max_length=50, verbose_name='講義詳細')),
                ('credit_num', models.IntegerField(choices=[(1, '1単位'), (2, '2単位'), (4, '4単位')], verbose_name='単位数')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university', verbose_name='大学名')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='講師名')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university', verbose_name='大学名')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='タグ名')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university', verbose_name='大学名')),
            ],
        ),
        migrations.CreateModel(
            name='scoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='採点方法')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university', verbose_name='大学名')),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='開講年')),
                ('season', models.CharField(max_length=10, verbose_name='開講時期')),
                ('attendants_check_frequency', models.CharField(max_length=20, verbose_name='出席確認の頻度')),
                ('credit_difficulty', models.IntegerField(verbose_name='単位の取りやすさ')),
                ('quality', models.IntegerField(verbose_name='講義内容の満足度')),
                ('opinion', models.CharField(blank=True, max_length=1000, null=True, verbose_name='コメント')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='投稿日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.class_info', verbose_name='講義名')),
                ('scoring_method', models.ManyToManyField(to='review.scoring', verbose_name='採点方法')),
                ('tag', models.ManyToManyField(to='review.tag')),
                ('teacher', models.ManyToManyField(to='review.teacher', verbose_name='担当教員名')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university', verbose_name='大学名')),
            ],
        ),
    ]
