# Generated by Django 4.0.3 on 2022-07-07 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='講義名')),
                ('subject_class', models.CharField(max_length=30, verbose_name='講義分類')),
                ('subject_detail', models.CharField(max_length=30, verbose_name='講義詳細')),
                ('credit_num', models.IntegerField(verbose_name='単位数')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university', verbose_name='大学名')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='タグ名')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='講師名')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university', verbose_name='大学名')),
            ],
        ),
        migrations.CreateModel(
            name='scoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='採点方法')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university', verbose_name='大学名')),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='開講年')),
                ('season', models.CharField(max_length=10, verbose_name='開講時期')),
                ('attendants_check_frequency', models.CharField(max_length=20, verbose_name='出席確認の頻度')),
                ('credit_difficulty', models.IntegerField(verbose_name='単位の取りやすさ')),
                ('quality', models.IntegerField(verbose_name='講義内容の満足度')),
                ('opinion', models.CharField(blank=True, max_length=500, null=True, verbose_name='コメント')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='投稿日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.class_info', verbose_name='講義名')),
                ('scoring_method', models.ManyToManyField(to='review.scoring', verbose_name='採点方法')),
                ('tag', models.ManyToManyField(to='review.tag')),
                ('teacher', models.ManyToManyField(to='review.teacher', verbose_name='担当教員名')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university', verbose_name='大学名')),
            ],
        ),
    ]
