# Generated by Django 4.0.3 on 2022-04-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='teacher',
        ),
        migrations.AddField(
            model_name='report',
            name='teacher',
            field=models.ManyToManyField(to='review.teacher', verbose_name='担当教員名'),
        ),
    ]
